### PR TITLE
Fix locating project output paths

### LINKED ISSUE #397: Add Visual Studio 2017 Support
The VS extension is currently not available for VS 2017. We should add that.

### LINKED ISSUE #429: "Could not find file: '<projectpath>\bin\Debug\net46\' from VSIX
I have a simple project that I have built and compiled in 4.6. I have confirmed that the complied .dll is available in <projectpath>\bin\Debug\net46\ directory . 

Downloaded and installed vsix for portability tool, in Visual Studio 2017.  When I attempt to run the addin I always get the following error with no other information provided.

```
Microsoft (R) .NET Portability Analyzer 1.0.0.0 (alpha)
Copyright (C) Microsoft Corporation. All rights reserved.
More information is available at http://go.microsoft.com/fwlink/?LinkId=506955

Detecting assembly references                      [Done]
* Could not find file: 'C:\src\acme\tfs\Core\Acme.Core\bin\Debug\net46\'
* No files were found to upload.

Finding source line information
                                                                    [Failed]
```

### PR DESCRIPTION
**Pull request by conniey**
* Fixes output path determination for projects. Before we would look for at a project for `<OutputFileName>` and stop if that property could not be determined.
* Supports .NET Core projects now. (Need to verify for project.json projects in VS2015.)
  * **Caveat**:  Released version Microsoft.Cci does not support portable PDB file structure, so it throws an OOM. As a result, I had to add this output window as a workaround... for now.  The repository has support for portable PDB, but I have no idea where the latest builds are. There is an issue here to get the builds: Microsoft/cci#46.
image
* Supports showing the proper projects for source line information. (Before, it would show the first project for all the source line information.)
image
* Fixes UI hangs due to async/await.  As a result, I used the ThreadHelper from this blog and ConfigureAwait(false): https://blogs.msdn.microsoft.com/andrewarnottms/2014/05/07/asynchronous-and-multithreaded-programming-within-vs-using-the-joinabletaskfactory/

Possibly fixes #429
Fixes #397, #390 

/cc: @twsouthwick

### CODE REVIEW

File: src/ApiPort.VisualStudio/Analyze/ProjectAnalyzer.cs [hunk 1]
```diff
@@ -38,23 +43,44 @@ public class ProjectAnalyzer
...
                 throw new PortabilityAnalyzerException(LocalizedStrings.UnableToBuildProject);
             }
 
             // TODO: Add option to include everything in output, not just build artifacts
-            var targetAssemblies = projects.SelectMany(p => p.GetAssemblyPaths()).ToList();
+            var targetAssemblies = new ConcurrentBag<string>();
+
+            foreach (var project in projects)
+            {
+                var output = await project.GetBuildOutputFilesAsync();
```
Comment (twsouthwick) [inline src/ApiPort.VisualStudio/Analyze/ProjectAnalyzer.cs]: `ConfigureAwait`? There's an analyzer we could add that will check for these

File: src/ApiPort.VisualStudio/Analyze/ProjectAnalyzer.cs [hunk 2]
```diff
@@ -79,21 +105,43 @@ private IEnumerable<string> GetAllAssembliesInDirectory(string directory)
...
+
+                var hierarchy = project.GetHierarchy();
+
+                foreach (var output in outputs)
+                {
+                    projectWithOutputMappings.AddOrUpdate(output, hierarchy, (existingKey, existingValue) => hierarchy);
+                }
+            }
+
+            await VisualStudio.ThreadHelper.JoinableTaskFactory.SwitchToMainThreadAsync();
```
Comment (twsouthwick) [inline src/ApiPort.VisualStudio/Analyze/ProjectAnalyzer.cs]: Do we need this again? I would expect us to still be on the main thread due to 115. The only await we have here doesn't have `ConfigureAwait` so it should be on the same context

File: src/ApiPort.VisualStudio/ApiPortVSPackage.cs [hunk 3]
```diff
@@ -68,7 +68,7 @@ protected override void Initialize()
                 mcs.AddCommand(analyzeMenuOptionsItem);
 
                 CommandID analyzeMenuToolbarCommandID = new CommandID(Guids.AnalyzeMenuItemCmdSet, (int)PkgCmdIDList.CmdIdAnalyzeToolbarMenuItem);
-                MenuCommand analyzeMenuToolbarItem = new MenuCommand((_, __) => ShowToolbar(), analyzeMenuToolbarCommandID);
+                MenuCommand analyzeMenuToolbarItem = new MenuCommand(async (_, __) => await ShowToolbarAsync(), analyzeMenuToolbarCommandID);
```
Comment (twsouthwick) [inline src/ApiPort.VisualStudio/ApiPortVSPackage.cs]: Does the `ShowToolbarAsync` need to be `async Task`? If it is only used as an event handler, you can just use `async void`

File: src/ApiPort.VisualStudio/ApiPortVSPackage.cs [hunk 4]
```diff
@@ -100,8 +100,12 @@ protected override void Initialize()
             }
         }
 
-        public void ShowToolbar()
+        public async System.Threading.Tasks.Task ShowToolbarAsync()
         {
+            // Calls to UI elements should use the main task thread.
+            // https://blogs.msdn.microsoft.com/andrewarnottms/2014/05/07/asynchronous-and-multithreaded-programming-within-vs-using-the-joinabletaskfactory/
+            await ThreadHelper.JoinableTaskFactory.SwitchToMainThreadAsync();
```
Comment (twsouthwick) [inline src/ApiPort.VisualStudio/ApiPortVSPackage.cs]: Not sure if VS does stuff differently, but UI events are generally called on the UI thread (at least in WPF/UWP)

File: src/ApiPort.VisualStudio/DteProjectExtensions.cs [hunk 5]
```diff
@@ -1,74 +1,189 @@
...
+        /// Tries to fetch output items if it uses Common Project System then
+        /// tries to fetch output items by retrieving FinalBuildOutput
+        /// location using code snippet from:
+        /// https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/tests/unittests/Tests.ProjectSystem.Miscellaneous.fs#L168-L182
+        /// </summary>
+        /// <returns>null if it is unable to retrieve VS configuration objects</returns>
+        public static async Task<IEnumerable<string>> GetBuildOutputFilesAsync(this Project project, CancellationToken cancellationToken = default(CancellationToken))
         {
-            var fileName = project.Properties.Item("OutputFileName").Value.ToString();
+            var output = await project?.GetBuildOutputFilesFromCPSAsync(cancellationToken);
```
Comment (twsouthwick) [inline src/ApiPort.VisualStudio/DteProjectExtensions.cs]: using the `?.` operator with `await` doesn't work - you'd end up with `await null;` which is not handled. Therefore, you'll need to explicitly check for null before calling this now.

File: src/ApiPort.VisualStudio/DteProjectExtensions.cs [hunk 6]
```diff
@@ -1,74 +1,189 @@
...
+                return output;
+            }
+
+            var configuration = GetVsProjectConfiguration(project);
+
+            if (configuration == null)
+            {
+                return null;
+            }
+            if (!(configuration is IVsProjectCfg2))
```
Comment (twsouthwick) [inline src/ApiPort.VisualStudio/DteProjectExtensions.cs]: This could be rewritten with pattern matching; ie `if(configuration is IVsProjectCfg2 configuration2)`. You'll have to swap the branching here, though

File: src/ApiPort.VisualStudio/Reporting/VsBrowserReportViewer.cs [hunk 7]
```diff
@@ -25,13 +26,13 @@ public VsBrowserReportViewer(IFileSystem fileSystem, TextWriter output, IVsWebBr
...
 
-        public void View(IEnumerable<string> urls)
+        public async Task ViewAsync(IEnumerable<string> urls)
         {
             foreach (var url in urls)
             {
                 if (IsHtml(url))
                 {
-                    ShowHtml(url);
+                    await ShowHtmlAsync(url);
```
Comment (twsouthwick) [inline src/ApiPort.VisualStudio/Reporting/VsBrowserReportViewer.cs]: `ConfigureAwait`?

File: src/ApiPort.VisualStudio/ApiPortVSPackage.cs (hunk 4 above)
Comment (conniey) [inline src/ApiPort.VisualStudio/ApiPortVSPackage.cs]: This method is called from the ProjectAnalyzer after analysis, which may not be on the main thread... I wanted to ensure we were always on it.

File: src/ApiPort.VisualStudio/ApiPortVSPackage.cs (hunk 3 above)
Comment (conniey) [inline src/ApiPort.VisualStudio/ApiPortVSPackage.cs]: Its used in the ProjectAnalyzer, so I didn't want to fire and forget about it.

File: src/ApiPort.VisualStudio/Analyze/ProjectAnalyzer.cs (hunk 2 above)
Comment (conniey) [inline src/ApiPort.VisualStudio/Analyze/ProjectAnalyzer.cs]: I added the analyzer and did ConfigureAwait(false) on everything, so its possible we wouldn't resume on the UI thread.

File: src/ApiPort.VisualStudio/DteProjectExtensions.cs (hunk 6 above)
Comment (conniey) [inline src/ApiPort.VisualStudio/DteProjectExtensions.cs]: 👍 I totally forgot about this feature.

**Comment by twsouthwick** [comment]
LGTM

**Comment by conniey** [comment]
@twsouthwick Should I merge this PR? I know it'll break VS2015 but will work for VS2017. :(
