### PR TITLE
Fix crash when opening report in VS

### LINKED ISSUE #402: Attempting to open an analysis report that has been deleted crashes VS
**Repro steps:**
* analyse a dll using the VS extension
* click on _Open directory_ in the _Portability Analysis Results_ tool window and delete/rename the report file
* click on _Open Report_ in the _Portability Analysis Results_

**Expected:**
Anything except a crash (e.g. a message box saying the file has been moved or deleted)

**Actual:**
VS crashes

### PR DESCRIPTION
**Pull request by twsouthwick**
This will check if the report (or directory) is available and if it is, will launch it. Otherwise, a notification is given and then the entries are removed from the pane. This change also moves to create the directory to output to if it is not already there

Fixes #402 and #359

### CODE REVIEW

File: src/ApiPort.VisualStudio/Models/OptionsModel.cs [hunk 1]
```diff
@@ -61,24 +61,13 @@ public IList<TargetPlatform> Platforms
...
-                    Directory.CreateDirectory(_outputDirectory);
-                }
-            }
+            set { UpdateProperty(ref _outputDirectory, value); }
         }
 
         public string DefaultOutputName
         {
             get { return _defaultOutputName; }
-            set
```
Comment (conniey) [inline src/ApiPort.VisualStudio/Models/OptionsModel.cs]: Is it possible that they'll set the DefaultOutputName to "" or null?

File: src/ApiPort.VisualStudio/Models/OptionsModel.cs [hunk 2]
```diff
@@ -61,24 +61,13 @@ public IList<TargetPlatform> Platforms
         public string OutputDirectory
         {
             get { return _outputDirectory; }
-            set
-            {
-                UpdateProperty(ref _outputDirectory, value);
```
Comment (conniey) [inline src/ApiPort.VisualStudio/Models/OptionsModel.cs]: The default SelectedPath for the dialog is "", so I was wondering if it was possible to press OK and not select a folder on the dialog.

File: src/ApiPort.VisualStudio/ViewModels/OutputViewModel.cs [hunk 3]
```diff
@@ -71,9 +103,7 @@ public DelegateCommand(Action<T> action)
 
             public void Execute(object parameter)
             {
-                var obj = parameter as T;
-
-                if (obj != null)
+                if (parameter is T obj)
```
Comment (conniey) [inline src/ApiPort.VisualStudio/ViewModels/OutputViewModel.cs]: 👍

File: src/ApiPort.VisualStudio/Models/OptionsModel.cs (hunk 2 above)
Comment (twsouthwick) [inline src/ApiPort.VisualStudio/Models/OptionsModel.cs]: Good point - I've updated this so it will check for null or whitespace and default to a reasonable place
